#server:
#  port: 8080
#
#spring:
#  application:
#    name: api-gateway
#
#  main:
#    web-application-type: reactive
#
#  cloud:
#    gateway:
#      server:
#        webflux:
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true
#          routes:
#            - id: user-service
#              uri: lb://user-service
#              predicates:
#                - Path=/users/**
#
#            - id: hotel-service
#              uri: lb://hotel-service
#              predicates:
#                - Path=/hotels/**
#
#            - id: rating-service
#              uri: lb://rating-service
#              predicates:
#                - Path=/ratings/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#
#
#
##server:
##  port: 8080
##
##spring:
##  application:
##    name: api-gateway
##  cloud:
##    gateway:
##      routes: # Corrected configuration path. This should be 'routes', not 'server.webflux.routes'.
##        - id: user-service
##          uri: lb://user-service # Using Eureka for load balancing
##          predicates:
##            - Path=/users/**
##          filters:
##            - AddRequestHeader=X-User-Service, true
##
##        - id: hotel-service
##          uri: lb://hotel-service # Using Eureka for load balancing
##          predicates:
##            - Path=/hotels/**
##          filters:
##            - AddRequestHeader=X-Hotel-Service, true
##
##        - id: review-service
##          uri: lb://review-service # Using Eureka for load balancing
##          predicates:
##            - Path=/reviews/**
##          filters:
##            - AddRequestHeader=X-Review-Service, true
##
##eureka:
##  client:
##    serviceUrl:
##      defaultZone: http://localhost:8761/eureka/